dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1          # HTTP клиент
  provider: ^6.1.2     # управление состоянием
  url_launcher: ^6.2.6 # открытие ссылок
  shared_preferences: ^2.2.2 # локальное хранилище
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  # если будет gRPC:
  grpc: ^3.2.4